ARG BASE_BRANCH
ARG SOURCE=/go/src/github.com/wangyd1988/lighthouse-inspur

FROM --platform=${BUILDPLATFORM} inspurwyd/shipyard-dapper-base:release-0.15-2 AS builder
ARG SOURCE
ARG TARGETPLATFORM

COPY . ${SOURCE}

RUN make -C ${SOURCE} LOCAL_BUILD=1 bin/${TARGETPLATFORM}/lighthouse-agent

FROM --platform=${TARGETPLATFORM} scratch
ARG SOURCE
ARG TARGETPLATFORM

WORKDIR /var/submariner

COPY --from=builder ${SOURCE}/bin/${TARGETPLATFORM}/lighthouse-agent /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/lighthouse-agent", "-alsologtostderr"]
